---
title: "Foundation Mathematics & Statistics in R"
author: Vi Tu (617634), Khoa Nguyen (), Amir Mohamed ()
output: html_notebook
---
```{r}
install.packages("ggplot2")
install.packages("tidyr")
install.packages("janitor")
install.packages("dplyr")
install.packages("shiny")
install.packages("tidyverse")
install.packages("matrixStats")
install.packages("e1071")
```


Load all the necessary packages for later use in the assignment
```{r}
library(ggplot2)
library(tidyr)
library(janitor)
library(dplyr)
library(shiny)
library(tidyverse)
library(matrixStats)
library(e1071)
```

```{r}
# Create a data frame based on the Excel file
Students <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k")
Course1 <- c(6.14, 8.20, 9.05, 5.54, 4.06, 3.14, 6.98, 8.55, 8.21, 9.94, 2.39)
Course2 <- c(7.70, 9.17, 9.77, 7.44, 9.41, 7.48, 6.13, 7.38, 7.53, 8.11, 9.41)
Course3 <- c(5.88, 8.28, 5.04, 8.49, 6.00, 8.62, 6.20, 8.13, 9.19, 9.43, 7.00)
Course4 <- c(2.80, 1.23, 7.98, 8.43, 1.81, 6.47, 3.40, 5.37, 3.39, 1.61, 0.72)
Course5 <- c(7.63, 5.19, 5.71, 6.60, 4.95, 6.91, 5.80, 6.83, 7.93, 5.35, 6.86)
Course6 <- c(8.43, 9.91, 8.58, 8.29, 10.00, 8.15, 8.93, 8.80, 8.61, 8.94, 9.59)
student_data <- data.frame(Students, Course1, Course2, Course3, Course4, Course5, Course6)
str(student_data)
view(student_data)
```

```{r}
# Convert the student names into row names
student_data2 <- student_data[,-1]
rownames(student_data2) <- student_data[,1]
view(student_data2)
student_data <- student_data2
```

```{r}
# Creating new columns to calculate Sum, Mean and Standard deviation, Skewness and Kurtosis of each STUDENT on student_data2
SumperStudent = rowSums(student_data2)
MeanperStudent = rowMeans(student_data2)
SDperStudent = apply(student_data2, 1, sd)
SkewperStudent = apply(student_data2, 1, skewness)
KurtosisperStudent = apply(student_data2, 1, kurtosis)
# Creating rows to calculate Sum, Mean and Standard deviation, Skewness and Kurtosis of each COURSE on student_data
SumperCourse = colSums(student_data2)
MeanperCourse = colMeans(student_data2)      
SDperCourse = c(sd(Course1), sd(Course2), sd(Course3), sd(Course4), sd(Course5), sd(Course6))
SkewperCourse = c(skewness(Course1), skewness(Course2), skewness(Course3), skewness(Course4), skewness(Course5), skewness(Course6))
KurtosisperCourse = c(kurtosis(Course1), kurtosis(Course2), kurtosis(Course3), kurtosis(Course4), kurtosis(Course5), kurtosis(Course6))
```


```{r}
# Add those new columns into the data frame
student_data2 <- cbind(student_data2, SumperStudent, MeanperStudent, SDperStudent, SkewperStudent, KurtosisperStudent)
# Add those new rows into the data frame
student_data2 <- rbind(student_data2, SumperCourse, MeanperCourse, SDperCourse, SkewperCourse, KurtosisperCourse)

# Change row names
rownames(student_data2)[rownames(student_data2) %in% c(12:16)] <- c("SumperCourse","MeanperCourse", "SDperCourse", "SkewnessperCourse", "KurtosisperCourse")
student_data2 <- student_data2 %>% mutate_if(is.numeric, round, digits = 2)
tail(student_data2)
```

Remove intersect values to NA?
```{r}
student_data2$SumperStudent[12:16] = NA # certain part of a column is returned to NA. Do the same way for other columns
student_data2$MeanperStudent[12:16] = NA
student_data2$SDperStudent[12:16] = NA
student_data2$SkewperStudent[12:16] = NA
student_data2$KurtosisperStudent[12:16] = NA
view(student_data2)
```

Create mean of means 
```{r}
# Per Course
meanC = apply(student_data2[13,1:6], 1, mean) #Calculate mean per means by Course 
SdC = apply(student_data2[14,1:6], 1, mean)
SkC = apply(student_data2[15,1:6], 1, mean)
KuC = apply(student_data2[16,1:6], 1, mean)
MoM_Course <- data.frame(meanC, SdC, SkC, KuC) #Create data frame for MoM per Course
View(MoM_Course)

# Per Student
meanS = mean(student_data2$MeanperStudent[1:11]) #Calculate mean per means by Student
SdS = mean(student_data2$SDperStudent[1:11])
SkS = mean(student_data2$SkewperStudent[1:11])
KuS = mean(student_data2$KurtosisperStudent[1:11])
MoM_Student <- data.frame(meanS, SdS, SkS, KuS) #Create data frame for MoM per Student
View(MoM_Student)

# Total dataframe
meanT = apply(student_data, 1, mean)
SdT = apply(student_data, 1, sd)
SkT = apply(student_data, 1, skewness)
KuT = apply(student_data, 1, kurtosis)

MoM_Total <- data.frame(meanT, SdT, SkT, KuT)
View(MoM_Total)
```


Plotting
